with source as (
    select *
    from {{ source('s3__bbrewington_nhl_data__moneypuck', 'game_level/all_teams') }}
),

renamed as (
    select
        team as team_abbr_raw,
        season as season_yr1,
        -- name as name,
        gameId::STRING as game_id,
        {{ game_id_attrs('gameId') }}
        playoffGame = 1 as is_playoff_game,
        -- playerTeam as player_team,
        opposingTeam as opposing_team_abbr,
        home_or_away as home_or_away,
        strptime(gameDate::STRING, '%Y%m%d')::DATE as game_date,
        position,
        situation,
        xGoalsPercentage as exp_goals_percentage,
        corsiPercentage as corsi_percentage,
        fenwickPercentage as fenwick_percentage,
        iceTime as ice_time,
        xOnGoalFor as exp_on_goal_for,
        xGoalsFor as exp_goals_for,
        xReboundsFor as exp_rebounds_for,
        xFreezeFor as exp_freeze_for,
        xPlayStoppedFor as exp_play_stopped_for,
        xPlayContinuedInZoneFor as exp_play_continued_in_zone_for,
        xPlayContinuedOutsideZoneFor as exp_play_continued_outside_zone_for,
        flurryAdjustedxGoalsFor as flurry_adjusted_exp_goals_for,
        scoreVenueAdjustedxGoalsFor as score_venue_adjusted_exp_goals_for,
        flurryScoreVenueAdjustedxGoalsFor as flurry_score_venue_adjusted_exp_goals_for,
        shotsOnGoalFor as shots_on_goal_for,
        missedShotsFor as missed_shots_for,
        blockedShotAttemptsFor as blocked_shot_attempts_for,
        shotAttemptsFor as shot_attempts_for,
        goalsFor as goals_for,
        reboundsFor as rebounds_for,
        reboundGoalsFor as rebound_goals_for,
        freezeFor as freeze_for,
        playStoppedFor as play_stopped_for,
        playContinuedInZoneFor as play_continued_in_zone_for,
        playContinuedOutsideZoneFor as play_continued_outside_zone_for,
        savedShotsOnGoalFor as saved_shots_on_goal_for,
        savedUnblockedShotAttemptsFor as saved_unblocked_shot_attempts_for,
        penaltiesFor as penalties_for,
        penalityMinutesFor as penality_minutes_for,
        faceOffsWonFor as face_offs_won_for,
        hitsFor as hits_for,
        takeawaysFor as takeaways_for,
        giveawaysFor as giveaways_for,
        lowDangerShotsFor as low_danger_shots_for,
        mediumDangerShotsFor as medium_danger_shots_for,
        highDangerShotsFor as high_danger_shots_for,
        lowDangerxGoalsFor as low_danger_exp_goals_for,
        mediumDangerxGoalsFor as medium_danger_exp_goals_for,
        highDangerxGoalsFor as high_danger_exp_goals_for,
        lowDangerGoalsFor as low_danger_goals_for,
        mediumDangerGoalsFor as medium_danger_goals_for,
        highDangerGoalsFor as high_danger_goals_for,
        scoreAdjustedShotsAttemptsFor as score_adjusted_shots_attempts_for,
        unblockedShotAttemptsFor as unblocked_shot_attempts_for,
        scoreAdjustedUnblockedShotAttemptsFor as score_adjusted_unblocked_shot_attempts_for,
        dZoneGiveawaysFor as d_zone_giveaways_for,
        xGoalsFromxReboundsOfShotsFor as exp_goals_from_exp_rebounds_of_shots_for,
        xGoalsFromActualReboundsOfShotsFor as exp_goals_from_actual_rebounds_of_shots_for,
        reboundxGoalsFor as rebound_exp_goals_for,
        totalShotCreditFor as total_shot_credit_for,
        scoreAdjustedTotalShotCreditFor as score_adjusted_total_shot_credit_for,
        scoreFlurryAdjustedTotalShotCreditFor as score_flurry_adjusted_total_shot_credit_for,
        xOnGoalAgainst as exp_on_goal_against,
        xGoalsAgainst as exp_goals_against,
        xReboundsAgainst as exp_rebounds_against,
        xFreezeAgainst as exp_freeze_against,
        xPlayStoppedAgainst as exp_play_stopped_against,
        xPlayContinuedInZoneAgainst as exp_play_continued_in_zone_against,
        xPlayContinuedOutsideZoneAgainst as exp_play_continued_outside_zone_against,
        flurryAdjustedxGoalsAgainst as flurry_adjusted_exp_goals_against,
        scoreVenueAdjustedxGoalsAgainst as score_venue_adjusted_exp_goals_against,
        flurryScoreVenueAdjustedxGoalsAgainst as flurry_score_venue_adjusted_exp_goals_against,
        shotsOnGoalAgainst as shots_on_goal_against,
        missedShotsAgainst as missed_shots_against,
        blockedShotAttemptsAgainst as blocked_shot_attempts_against,
        shotAttemptsAgainst as shot_attempts_against,
        goalsAgainst as goals_against,
        reboundsAgainst as rebounds_against,
        reboundGoalsAgainst as rebound_goals_against,
        freezeAgainst as freeze_against,
        playStoppedAgainst as play_stopped_against,
        playContinuedInZoneAgainst as play_continued_in_zone_against,
        playContinuedOutsideZoneAgainst as play_continued_outside_zone_against,
        savedShotsOnGoalAgainst as saved_shots_on_goal_against,
        savedUnblockedShotAttemptsAgainst as saved_unblocked_shot_attempts_against,
        penaltiesAgainst as penalties_against,
        penalityMinutesAgainst as penality_minutes_against,
        faceOffsWonAgainst as face_offs_won_against,
        hitsAgainst as hits_against,
        takeawaysAgainst as takeaways_against,
        giveawaysAgainst as giveaways_against,
        lowDangerShotsAgainst as low_danger_shots_against,
        mediumDangerShotsAgainst as medium_danger_shots_against,
        highDangerShotsAgainst as high_danger_shots_against,
        lowDangerxGoalsAgainst as low_danger_exp_goals_against,
        mediumDangerxGoalsAgainst as medium_danger_exp_goals_against,
        highDangerxGoalsAgainst as high_danger_exp_goals_against,
        lowDangerGoalsAgainst as low_danger_goals_against,
        mediumDangerGoalsAgainst as medium_danger_goals_against,
        highDangerGoalsAgainst as high_danger_goals_against,
        scoreAdjustedShotsAttemptsAgainst as score_adjusted_shots_attempts_against,
        unblockedShotAttemptsAgainst as unblocked_shot_attempts_against,
        scoreAdjustedUnblockedShotAttemptsAgainst as score_adjusted_unblocked_shot_attempts_against,
        dZoneGiveawaysAgainst as d_zone_giveaways_against,
        xGoalsFromxReboundsOfShotsAgainst as exp_goals_from_exp_rebounds_of_shots_against,
        xGoalsFromActualReboundsOfShotsAgainst as exp_goals_from_actual_rebounds_of_shots_against,
        reboundxGoalsAgainst as rebound_exp_goals_against,
        totalShotCreditAgainst as total_shot_credit_against,
        scoreAdjustedTotalShotCreditAgainst as score_adjusted_total_shot_credit_against,
        scoreFlurryAdjustedTotalShotCreditAgainst as score_flurry_adjusted_total_shot_credit_against
    from source
),

calc as (
    select * from renamed
)

select *
from calc
